{% set name = "embeam" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/embeam-{{ version }}.tar.gz
  sha256: 7c5454d5e4e2ec9a4e922dcc8d7c81979a1415bffdd9bdb7741062a6484eb772

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - empix
    - hyperspy
    - pyfai

test:
  imports:
    - embeam
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/embeam/
  summary: A Python library for for modelling beams and lenses in electron microscopy.
  dev_url: https://github.com/mrfitzpa/embeam
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
